# Generated by Django 4.2.6 on 2023-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_date_birth_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('A', 'Approved'), ('NA', 'Not Approved')], default='W', max_length=2),
        ),
    ]
